job1:
  script: sleep 10

job2:
  script: sleep 10

job3:
  script: sleep 10

job4:
  script: sleep 10

job5:
  script: sleep 10

job6:
  script: sleep 10

job7:
  script: sleep 10

job8:
  script: sleep 10

