stages:
  - deploy
  - test-deploy

deploy:
  stage: deploy
  script: echo Run deploy ... && false
  when: manual
  allow_failure: false


test-deploy:
  stage: test-deploy
  script: echo Run deploy ...