# .gitlab-ci.yml

Build Frontend:
  script: echo Build Frontend ...
  rules:
    - changes:
        paths:
          - frontend/**
        compare_to: 'refs/heads/main'

Build Backend:
  script: echo Build Backend ...
  rules:
    - changes:
        paths:
          - backend/**
        compare_to: 'refs/heads/main'
