image: sikalabs/ci


test2:
  script:
    - kubectl --help

test:
  image: ondrejsika/pytest
  # image: python:3-slim
  script:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml